### ISSUE TITLE
IllegalStateException crash when creating EasyDialog: specified child already has a parent

### ISSUE THREAD

**Issue by garygcchiu** [michaelye/EasyDialog#42]
Stack log: 

> java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
>                                                                             at android.view.ViewGroup.addViewInner(ViewGroup.java:5122)
>                                                                             at android.view.ViewGroup.addView(ViewGroup.java:4953)
>                                                                             at android.view.ViewGroup.addView(ViewGroup.java:4893)
>                                                                             at android.view.ViewGroup.addView(ViewGroup.java:4866)
>                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1309)
>                                                                             at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
>                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
>                                                                             at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
>                                                                             at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
>                                                                             at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
>                                                                             at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
>                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
>                                                                             at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
>                                                                             at android.os.Handler.handleCallback(Handler.java:789)
>                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
>                                                                             at android.os.Looper.loop(Looper.java:164)
>                                                                             at android.app.ActivityThread.main(ActivityThread.java:6938)
>                                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
>                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
> 

My code:

```
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState){
    setHasOptionsMenu(true);
    final View view = inflater.inflate(R.layout.this_fragments_layout, container, false);

    new EasyDialog(mainActivity)
            // .setLayoutResourceId(R.layout.layout_tip_content_horizontal)//layout resource id
            .setLayout(view)
            .setBackgroundColor(mainActivity.getResources().getColor(R.color.background_color_black))
            .setLocation(new int[]{300, 300})//point in screen
            //.setLocationByAttachedView(btnTopLeft)
            .setGravity(EasyDialog.GRAVITY_BOTTOM)
            .setAnimationTranslationShow(EasyDialog.DIRECTION_X, 1000, -600, 100, -50, 50, 0)
            .setAnimationAlphaShow(1000, 0.3f, 1.0f)
            .setAnimationTranslationDismiss(EasyDialog.DIRECTION_X, 500, -50, 800)
           .setAnimationAlphaDismiss(500, 1.0f, 0.0f)
            .setTouchOutsideDismiss(true)
            .setMatchParent(true)
            .setMarginLeftAndRight(24, 24)
            .setOutsideColor(mainActivity.getResources().getColor(R.color.background_color_black))
            .show();
```

I am creating the EasyDialog inside a Fragment. If I don't call show(), then the crash does not occur. I am not sure which child already has a parent. Am I doing something wrong?

**Comment by eco4ndly** [comment]
While creating the view pass `null` in place of `container`
